[package]
authors = ["James Gilles <jhgilles@mit.edu>"]
name = "battlecode_hackathon"
version = "0.1.0"

[dependencies]
error-chain = "0.11.0"
fnv = "1.0.5"
serde = "1.0.15"
serde_derive = "1.0.15"
serde_json = "1.0.3"
